version: '3.8'

services:
  rag-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./Dataset_ABA:/app/Dataset_ABA
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
